---
en:
  languageName: "English"
  contentDir: "content/en"
  weight: 100

ja:
  languageName: "日本語"
  contentDir: "content/ja"
  weight: 90

zh-TW:
  languageName: "繁體中文"
  contentDir: "content/zh-TW"
  weight: 80
